### ISSUE TITLE
piorytety błąd podczas robienia planu

### ISSUE THREAD

**Issue by ddnowicki** [Luzyce/Luzyce#7]
```
script.min.js:1  Uncaught TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.

    at script.min.js:1:1020

2dotnet.runtime.8.0.10.92aq6ohvf8.js:3 info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]

      Authorization failed. These requirements were not met:

      DenyAnonymousAuthorizationRequirement: Requires an authenticated user.

blazor.webassembly.js:1 productWarehousesStocks:

blazor.webassembly.js:1 ProductId: 8, Quantity: 0

blazor.webassembly.js:1 ProductId: 4068, Quantity: 28

blazor.webassembly.js:1  crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]

      Unhandled exception rendering component: Cannot read properties of undefined (reading 'backdrop')

      TypeError: Cannot read properties of undefined (reading 'backdrop')

          at Modal._initializeBackDrop (https://app-phs.cloudsolutions.ovh/js/bootstrap.bundle.js:4336:41)

          at new Modal (https://app-phs.cloudsolutions.ovh/js/bootstrap.bundle.js:4268:29)

          at openModal (<anonymous>:3:21)

          at https://app-phs.cloudsolutions.ovh/_framework/blazor.webassembly.js:1:2878

          at new Promise (<anonymous>)

          at g.beginInvokeJSFromDotNet (https://app-phs.cloudsolutions.ovh/_framework/blazor.webassembly.js:1:2835)

          at Object.bn [as invokeJSJson] (https://app-phs.cloudsolutions.ovh/_framework/blazor.webassembly.js:1:58561)

          at https://app-phs.cloudsolutions.ovh/_framework/dotnet.runtime.8.0.10.92aq6ohvf8.js:3:178446

          at Ll (https://app-phs.cloudsolutions.ovh/_framework/dotnet.runtime.8.0.10.92aq6ohvf8.js:3:179280)

          at [https://app-phs.cloudsolutions.ovh/_framework/dotnet.native.wasm:wasm-function[349]:0x1f99a](https://app-phs.cloudsolutions.ovh/_framework/dotnet.native.wasm:wasm-function%5b349%5d:0x1f99a)

Microsoft.JSInterop.JSException: Cannot read properties of undefined (reading 'backdrop')

TypeError: Cannot read properties of undefined (reading 'backdrop')

    at Modal._initializeBackDrop (https://app-phs.cloudsolutions.ovh/js/bootstrap.bundle.js:4336:41)

    at new Modal (https://app-phs.cloudsolutions.ovh/js/bootstrap.bundle.js:4268:29)

    at openModal (<anonymous>:3:21)

    at https://app-phs.cloudsolutions.ovh/_framework/blazor.webassembly.js:1:2878

    at new Promise (<anonymous>)

    at g.beginInvokeJSFromDotNet (https://app-phs.cloudsolutions.ovh/_framework/blazor.webassembly.js:1:2835)

    at Object.bn [as invokeJSJson] (https://app-phs.cloudsolutions.ovh/_framework/blazor.webassembly.js:1:58561)

    at https://app-phs.cloudsolutions.ovh/_framework/dotnet.runtime.8.0.10.92aq6ohvf8.js:3:178446

    at Ll (https://app-phs.cloudsolutions.ovh/_framework/dotnet.runtime.8.0.10.92aq6ohvf8.js:3:179280)

    at [https://app-phs.cloudsolutions.ovh/_framework/dotnet.native.wasm:wasm-function[349]:0x1f99a](https://app-phs.cloudsolutions.ovh/_framework/dotnet.native.wasm:wasm-function%5b349%5d:0x1f99a)

   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.Infrastructure.IJSVoidResult, Microsoft.JSInterop, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()

   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime , String , Object[] )

   at Luzyce.WebApp.Pages.ProductionPriorities.NewProdPriorities.CheckParametersAndHandleClick()

   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)

   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task , ComponentState )

Ft @ blazor.webassembly.js:1
```

**Comment by ddnowicki** [comment]
nie udalo sie odtworzyc bledu
